#!/bin/sh
set -eu
eval "$(/usr/bin/python3 /usr/local/share/t630/t630_account.py env)"
test "$(/usr/bin/id -u)" = "$T630_OWNER_UID"
export GTK_IM_MODULE=t630-wayland
export GTK_IM_MODULE_FILE=/usr/local/share/t630/gtk-immodules.cache
exec 9>"$XDG_RUNTIME_DIR/t630-session-start.lock"
/usr/bin/flock 9
if ! /usr/bin/dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply / org.freedesktop.DBus.ListNames >/dev/null 2>&1; then
    /usr/bin/dbus-daemon --session --fork --address="$DBUS_SESSION_BUS_ADDRESS" 9>&-
fi
/usr/bin/flock -u 9
exec 9>&-
cd "$T630_OWNER_HOME"
case "${1:-}" in
    files) exec /usr/bin/thunar "$T630_OWNER_HOME/Documents" ;;
    editor) exec /usr/bin/mousepad ;;
    terminal) exec /usr/bin/xfce4-terminal --disable-server --default-working-directory="$T630_OWNER_HOME" ;;
    *) exit 2 ;;
esac
